project:
  type: website
  output-dir: docs
  preview: 
    watch-inputs: false

website:
  title: "LANDFIRE-Powered Landscape Assessment"
  navbar:
    search: TRUE
    pinned: true
    left:
      - href: index.qmd
        text: Home
        
      - href: download.qmd
        text: Download data
        
      - href: prep_rasters.qmd
        text: Prepare rasters

      - href: make_charts.qmd
        text: Make charts
        
      - href: make_hex_map.qmd
        text: Make hex map
        
      - href: about.qmd
        text: About

format:
  html:
    page-layout: full
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-expand: 3
    
editor: source
