---
title: "About this Project"
---

## (Don't) Start from Scratch

Welcome to LANDFIRE R Toolkit — your go-to hub for accelerating landscape analysis with LANDFIRE and R. Here, you'll find tested, ready-to-use R code that simplifies data access, processing, and visualization for your region. Whether you're a seasoned analyst or just getting started, this site helps you fast-track your workflow and connect with a growing community of LANDFIRE users who are actively coding, sharing, and tackling real-world challenges.

## LANDFIRE & The Nature Conservancy 

[LANDFIRE](https://landfire.gov){target="blank"} (Landscape Fire and Resource Management Planning Tools) LANDFIRE is a shared interagency wildland fire management data program across the United States and Territories. Leadership, management, and oversight are through the U.S. Department of Agriculture Forest Service - Fire and Aviation Management and the U.S. Department of the Interior – Office of Wildland Fire. 

LANDFIRE provides more than twenty landscape-scale geospatial products of biological and ecological data, including (900+) vegetation types and (13/40) fire behavior fuel models that support all-lands planning, fire and natural resources management, operations, analyses and assessments.  

**Project Team:** [USGS EROS](https://www.usgs.gov/centers/eros){target="blank"}, EROS Technical Support Services Contract (KBR), [The Nature Conservancy](https://www.nature.org/en-us/){target="blank"}, [USDA Forest Service (Rocky Mountain Research Station) RMRS](https://research.fs.usda.gov/rmrs){target="blank"}, [Forest Inventory & Analysis (FIA)](https://research.fs.usda.gov/programs/fia){target="blank"} 

**Partners:** [USGS Gap Analysis](https://www.usgs.gov/programs/gap-analysis-project){target="blank"}, [National Land Imaging Programs](https://www.usgs.gov/programs/national-land-imaging-program){target="blank"} 

[The Nature Conservancy (TNC)](https://landfire.gov/about-landfire/lf-team){target="blank"} is part of the Project Team, supported by a cooperative agreement through USDA Forest Service. TNC’s LANDFIRE Team works closely with the LANDFIRE Business Leads, program staff, and other partners to provide support to LANDFIRE and the user community by: 

* Helping users understand the strengths, weaknesses, and appropriate uses of LANDFIRE products. 

* Locating, obtaining, and using geospatial data, tools, and models for fire and natural resource management, planning, and implementation. 

* Identifying and comparing management priorities, evaluating threats to ecosystems, and exploring outcomes under alternative management scenarios. 


> TNC’s LANDFIRE Team is advancing conservation outcomes through collaborative ecosystem science by supporting LANDFIRE users as they locate, obtain and apply the diverse suite of LANDFIRE products and data.




## Still have questions? LANDFIRE is here to help. 

Ask the [LANDFIRE Helpdesk](mailto:helpdesk@landfire.gov){target="blank"} 

Search the [LANDFIRE Helpdesk Dashboard](https://landfire.gov/helpdesk ){target="blank"} (see what others are asking and find solutions to common problems) 

Search (& subscribe to) the [LANDFIRE YouTube Channel](https://www.youtube.com/@LANDFIREvideo){target="blank} (see tutorials, Office Hours, quick demonstrations) 