---
title: "Make charts with LANDFIRE data"
---



## Skills learned

Use this page to:

- Practice summarizing LANDFIRE Biophysical Settings data using R to identify dominant vegetation types across the example landscape
- Create bar charts to visualize relative percentages and acerage, gaining experience in data grouping, plotting, and interpretation

## Set up

To run the code below you will need to:

1. Work through the preceding pages, [Download data](docs/download.html){target="blank"} and [Prepare rasters](docs/prep_rasters.html){target="blank"} for your own Area of Interest OR
2. Make sure you have a datasheet with BpS names and Relative Percentages at the least. We will load in the data for our Area of Interest for you to work with if you do not have your own data.



### Code to load packages and inputs, summarize data

```{r}
#| label: Load packages and data
#| echo: true
#| message: false
#| warning: false
#| code-overflow: wrap
#| include: true
#| results: hide


# load packages
library(tidyverse)
library(scales)
library(stringr)

# read in data for our Area of Interest
bps_data <- read.csv("outputs/bps_aoi_attributes.csv")
evt_data <- read.csv("outputs/evt_aoi_attributes.csv")

# summarize data by BpS Name attribute for chart.  We do this as an AoI may have multiple variants if it crosses multiple Map Zones. We also limit output dataframe to the top 10 BpSs.  Customize as needed!

bps_name <- bps_data %>%
  group_by(BPS_NAME) %>%
  summarize(ACRES = sum(ACRES),
            REL_PERCENT = sum(REL_PERCENT)) %>%
  arrange(desc(REL_PERCENT)) %>%
  top_n(n = 10, wt = REL_PERCENT)

# plot
bps_percent_chart <- 
  ggplot(data = bps_name, aes(x = BPS_NAME, y = REL_PERCENT)) + 
  geom_bar(stat = "identity") +
  labs(
    title = "Top 10 Biophysical Settings",
    subtitle = "Represents dominant vegetation systems pre-European colonization",
    caption = "Data from landfire.gov.",
    x = "",
    y = "Percent of landscape") +
  scale_x_discrete(limits = rev(bps_name$BPS_NAME),
                   labels = function(x) str_wrap(x, width = 18)) +
  coord_flip() +
  theme_bw(base_size = 14)


bps_acres_chart <-
  ggplot(data = bps_name, aes(x = BPS_NAME, y = ACRES)) + 
  geom_bar(stat = "identity") +
  labs(
    title = "Top 10 Biophysical Settings",
    subtitle = "Represents dominant vegetation systems pre-European colonization",
    caption = "Data from landfire.gov.",
    x = "",
    y = "Acres") +
  scale_x_discrete(limits = rev(bps_name$BPS_NAME),
                   labels = function(x) str_wrap(x, width = 18)) +
  coord_flip() +
  theme_bw(base_size = 14) +
  scale_y_continuous(labels = comma)

bps_acres_chart






```





